from .io import FAL_INPUT_NODES, FAL_IO_HELPER_NODES
from .io import NODE_DISPLAY_NAME_MAPPINGS as IO_NODE_DISPLAY_NAME_MAPPINGS
from .loader import NODE_CLASS_MAPPINGS as LOADER_NODE_CLASS_MAPPINGS
from .loader import NODE_DISPLAY_NAME_MAPPINGS as LOADER_NODE_DISPLAY_NAME_MAPPINGS

# Import new model nodes
from .image import FAL_IMAGE_NODES, FAL_IMAGE_DISPLAY_NAMES
from .video import FAL_VIDEO_NODES, FAL_VIDEO_DISPLAY_NAMES

NODE_CLASS_MAPPINGS = {
    **FAL_INPUT_NODES,
    **FAL_IO_HELPER_NODES,
    **LOADER_NODE_CLASS_MAPPINGS,
    **FAL_IMAGE_NODES,
    **FAL_VIDEO_NODES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IO_NODE_DISPLAY_NAME_MAPPINGS,
    **LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **FAL_IMAGE_DISPLAY_NAMES,
    **FAL_VIDEO_DISPLAY_NAMES,
}
